MONEY_COLUMNS = [
    "contract_amount",
    "target_cost",
    "actual_cost",
    "received_amount",
    "paid_amount",
    "profit",
    "amount",
    "settlement_amount",
    "invoice_amount",
    "receivable",
    "payable",
    "budget_unit_price",
    "purchase_unit_price",
    "total_amount",
    "rental_price",
    "rental_amount",
    "claim_amount",
    "paid",
    "unpaid",
]

PROJECT_DISPLAY_COLUMNS = {
    "project_no": "项目编号",
    "project_name": "项目名称",
    "project_type": "项目类型",
    "voltage_level": "电压等级",
    "owner": "建设单位",
    "project_manager": "项目经理",
    "status": "项目状态",
    "planned_start": "计划开始",
    "planned_end": "计划结束",
    "contract_amount": "合同金额",
    "target_cost": "目标成本",
    "actual_cost": "实际成本",
    "received_amount": "已收款",
    "paid_amount": "已付款",
    "output_progress": "产值进度",
    "collection_progress": "收款进度",
    "cost_ratio": "成本比",
    "profit_rate": "利润率",
    "risk_level": "风险等级",
    "document_completion": "资料完整率",
}

GLOBAL_COLUMN_MAP = {
    "id": "ID",
    "project_id": "项目ID",
    "project_no": "项目编号",
    "project_name": "项目名称",
    "project_type": "项目类型",
    "voltage_level": "电压等级",
    "address": "项目地址",
    "owner": "建设单位",
    "constructor": "施工单位",
    "designer": "设计单位",
    "supervisor": "监理单位",
    "project_manager": "项目经理",
    "status": "项目状态",
    "planned_start": "计划开始",
    "planned_end": "计划结束",
    "actual_start": "实际开始",
    "actual_end": "实际结束",
    "contract_amount": "合同金额",
    "target_cost": "目标成本",
    "actual_cost": "实际成本",
    "received_amount": "已收款",
    "paid_amount": "已付款",
    "output_progress": "产值进度",
    "collection_progress": "收款进度",
    "document_completion": "资料完整率",
    "cost_ratio": "成本比",
    "profit": "当前利润",
    "expected_profit": "预计利润",
    "profit_rate": "利润率",
    "risk_level": "风险等级",
    "contract_no": "合同编号",
    "contract_name": "合同名称",
    "contract_type": "合同类型",
    "party_a": "甲方",
    "party_b": "乙方",
    "settlement_amount": "结算金额",
    "invoice_amount": "发票金额",
    "receivable": "应收款",
    "payable": "应付款",
    "contract_status": "合同状态",
    "approval_status": "审批状态",
    "archive_status": "归档状态",
    "cost_category": "成本分类",
    "sign_date": "签订日期",
    "cost_no": "成本编号",
    "cost_type": "成本类型",
    "contract_id": "关联合同",
    "supplier": "供应商/分包商",
    "amount": "金额",
    "occur_date": "发生日期",
    "handler": "经办人",
    "invoice_status": "发票状态",
    "payment_status": "付款状态",
    "material_code": "材料编码",
    "material_name": "材料名称",
    "category": "分类",
    "specification": "规格型号",
    "unit": "单位",
    "quantity": "数量",
    "budget_unit_price": "预算单价",
    "purchase_unit_price": "采购单价",
    "total_amount": "总金额",
    "purchase_contract_id": "采购合同",
    "delivery_status": "到货状态",
    "warehouse_status": "入库状态",
    "usage_status": "领用状态",
    "stock_quantity": "库存数量",
    "safe_stock": "安全库存",
    "is_over_price": "是否超价",
    "is_shortage": "是否缺货",
    "equipment_no": "设备编号",
    "equipment_name": "设备名称",
    "owner_unit": "所属单位",
    "current_status": "当前状态",
    "use_start": "使用开始日期",
    "use_end": "使用结束日期",
    "rental_price": "租赁单价",
    "rental_amount": "租赁金额",
    "maintenance_status": "保养状态",
    "repair_status": "维修状态",
    "responsible_person": "责任人",
    "node_name": "节点名称",
    "planned_finish": "计划完成",
    "actual_finish": "实际完成",
    "is_delayed": "是否延期",
    "attachment": "附件",
    "finance_no": "资金编号",
    "finance_type": "业务类型",
    "counterparty": "往来单位",
    "direction": "方向",
    "business_date": "业务日期",
    "invoice_type": "发票类型",
    "plan_status": "计划状态",
    "workflow_no": "流程编号",
    "workflow_type": "流程类型",
    "title": "标题",
    "initiator": "发起人",
    "current_node": "当前节点",
    "current_handler": "当前处理人",
    "start_time": "发起时间",
    "arrival_time": "到达时间",
    "is_overdue": "是否超时",
    "approval_result": "审批结果",
    "approval_opinion": "审批意见",
    "trace": "流程轨迹",
    "record_no": "记录编号",
    "issue_type": "问题类型",
    "issue_level": "问题等级",
    "found_by": "发现人",
    "found_date": "发现日期",
    "rectify_deadline": "整改期限",
    "rectify_requirement": "整改要求",
    "rectify_status": "整改状态",
    "review_result": "复查结果",
    "is_closed": "是否闭环",
    "document_no": "资料编号",
    "document_name": "资料名称",
    "document_type": "资料类型",
    "uploader": "上传人",
    "upload_time": "上传时间",
    "audit_status": "审核状态",
    "is_required": "是否必传",
    "is_missing": "是否缺失",
    "version": "版本号",
    "file_path": "附件路径",
    "risk_no": "风险编号",
    "risk_type": "风险类型",
    "trigger_reason": "触发原因",
    "risk_indicator": "风险指标",
    "deadline": "截止时间",
    "recommended_action": "建议动作",
    "current_status": "当前状态",
}

RISK_LEVEL_ORDER = {"低": 1, "中": 2, "高": 3, "严重": 4}
